import Link from "next/link";
import { AppShell } from "@/src/components/app-shell";

export default function HomePage() {
  return (
    <AppShell active="home">
      <header className="flex flex-col gap-2 border-b border-[#dbe4ef] pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-[#1664d8]">Tuesday, September 8</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[#10233f]">Good morning, Alex</h1><p className="mt-2 text-sm text-[#60738c]">Here is a clear view of what deserves your attention today.</p></div><Link href="/profile" className="hidden h-10 w-10 items-center justify-center rounded-full bg-[#dceaff] text-sm font-semibold text-[#1557b5] ring-4 ring-white sm:flex" aria-label="Open profile">A</Link></header>
      <section className="mt-7 rounded-2xl bg-[#155fcf] p-6 text-white shadow-[0_16px_35px_rgba(21,95,207,0.2)] sm:p-8" aria-labelledby="focus-heading"><div className="flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><div className="max-w-xl"><p className="text-sm font-medium text-blue-100">Your next best step</p><h2 id="focus-heading" className="mt-3 text-3xl font-semibold tracking-tight">Protect your deep work window.</h2><p className="mt-3 text-sm leading-6 text-blue-100">You have 90 minutes before your product sync. Use it to finish the architecture draft while your energy is highest.</p></div><Link href="/focus-home" className="inline-flex w-fit items-center rounded-lg bg-white px-4 py-3 text-sm font-semibold text-[#1557b5] transition hover:bg-blue-50">Start focus session <span className="ml-3" aria-hidden="true">→</span></Link></div></section>
      <div className="mt-7 grid gap-5 lg:grid-cols-[1.35fr_0.65fr]">
        <section className="rounded-2xl border border-[#dbe4ef] bg-white p-5 shadow-sm" aria-labelledby="tasks-heading"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#7b8da5]">Today</p><h2 id="tasks-heading" className="mt-1 text-lg font-semibold text-[#10233f]">Your priorities</h2></div><Link href="/tasks-inbox" className="text-sm font-semibold text-[#1664d8] hover:text-[#0d4fac]">View tasks</Link></div><div className="mt-5 divide-y divide-[#edf1f6]"><div className="flex items-center gap-3 py-3"><span className="flex h-5 w-5 items-center justify-center rounded-full border-2 border-[#1664d8] text-xs text-[#1664d8]">✓</span><div className="flex-1"><p className="text-sm text-[#7b8da5] line-through">Review product spec document</p><p className="mt-1 text-xs text-[#9aa9ba]">Completed at 9:30 AM</p></div></div><div className="flex items-center gap-3 py-3"><span className="h-5 w-5 rounded-full border-2 border-[#b4c3d4]" /><div className="flex-1"><p className="text-sm font-medium text-[#243b5a]">Finish app architecture draft</p><p className="mt-1 text-xs text-[#7b8da5]">Due today at 2:00 PM · Work</p></div><span className="h-2 w-2 rounded-full bg-[#1664d8]" /></div><div className="flex items-center gap-3 py-3"><span className="h-5 w-5 rounded-full border-2 border-[#b4c3d4]" /><div className="flex-1"><p className="text-sm font-medium text-[#243b5a]">Prepare product sync notes</p><p className="mt-1 text-xs text-[#7b8da5]">Due today at 4:30 PM · Work</p></div><span className="h-2 w-2 rounded-full bg-[#f2a33a]" /></div></div></section>
        <section className="rounded-2xl border border-[#dbe4ef] bg-white p-5 shadow-sm" aria-labelledby="progress-heading"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#7b8da5]">This week</p><h2 id="progress-heading" className="mt-1 text-lg font-semibold text-[#10233f]">Your progress</h2><div className="mt-6 flex items-center gap-4"><div className="flex h-20 w-20 items-center justify-center rounded-full border-[7px] border-[#dceaff] border-t-[#1664d8] text-xl font-semibold text-[#10233f]">68%</div><div><p className="text-sm font-medium text-[#243b5a]">Good momentum</p><p className="mt-1 text-xs leading-5 text-[#7b8da5]">12 of 18 priorities completed</p></div></div><div className="mt-6 grid grid-cols-2 gap-3 border-t border-[#edf1f6] pt-4"><div><p className="text-xl font-semibold text-[#10233f]">4h 20m</p><p className="mt-1 text-xs text-[#7b8da5]">Focus time</p></div><div><p className="text-xl font-semibold text-[#10233f]">7</p><p className="mt-1 text-xs text-[#7b8da5]">Notes captured</p></div></div></section>
      </div>
      <section className="mt-5 rounded-2xl border border-[#dbe4ef] bg-white p-5 shadow-sm" aria-labelledby="assistant-heading"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#e6f0ff] text-sm font-semibold text-[#1664d8]">Z</span><h2 id="assistant-heading" className="text-lg font-semibold text-[#10233f]">Work with Zenvyx AI</h2></div><p className="mt-2 text-sm text-[#7b8da5]">Plan, capture, and make decisions in one conversation.</p></div><Link href="/ai-chat" className="inline-flex w-fit items-center rounded-lg bg-[#eaf2ff] px-4 py-2.5 text-sm font-semibold text-[#1664d8] transition hover:bg-[#dceaff]">Open chat <span className="ml-3" aria-hidden="true">→</span></Link></div></section>
    </AppShell>
  );
}
