"use client";

import { useState } from "react";
import Link from "next/link";
import { PhoneFrame } from "@/src/app/onboarding/page";
import { AppBackButton } from "@/src/components/app-navigation";

const primaryButton = "rounded-lg bg-gradient-to-r from-[#4940ec] to-[#8c4eed] py-3 text-[10px] font-bold shadow-[0_7px_18px_rgba(100,71,238,0.3)]";

function BackHeader({ title, action }: { title: string; action?: string }) {
  return <div className="flex items-center gap-3"><AppBackButton fallback="/profile" /><h2 className="text-[16px] font-extrabold">{title}</h2>{action && <span className="ml-auto text-[8px] text-white/60">{action}</span>}</div>;
}

function Toggle({ active, onClick }: { active: boolean; onClick: () => void }) {
  return <button type="button" aria-label="Toggle setting" onClick={onClick} className={`h-3.5 w-6 rounded-full p-0.5 ${active ? "bg-[#00c7e5]" : "bg-white/15"}`}><span className={`block h-2.5 w-2.5 rounded-full bg-white transition-transform ${active ? "translate-x-2.5" : ""}`} /></button>;
}

function SettingRow({ label, value, active, onClick }: { label: string; value?: string; active?: boolean; onClick?: () => void }) {
  return <div className="flex items-center justify-between rounded-lg border border-white/5 bg-[#110d28] px-2.5 py-2.5 text-[8px]"><span>{label}</span>{typeof active === "boolean" && onClick ? <Toggle active={active} onClick={onClick} /> : <span className="text-white/45">{value} {value !== "Secured" && "›"}</span>}</div>;
}

export function SettingsMainScreen() {
  const [settings, setSettings] = useState([true, false, true]);
  const [accent, setAccent] = useState("cyan");
  const flip = (index: number) => setSettings((current) => current.map((value, itemIndex) => itemIndex === index ? !value : value));
  return <PhoneFrame><div className="relative min-h-[555px] pb-5 pt-5"><BackHeader title="Settings" /><p className="mb-2 mt-6 text-[7px] font-bold uppercase text-white/50">Appearance parameters</p><div className="space-y-1.5 rounded-xl border border-white/5 bg-[#110d28] p-2"><div className="flex justify-between text-[7px] text-white/60"><span>System</span><span>Light</span><span className="rounded border border-white/10 px-2 py-1 text-white">Dark</span></div><div className="mt-2 flex items-center justify-between text-[7px]"><span>Accent Color Space</span><span className="flex gap-1.5">{[["cyan", "#00c7e5"], ["purple", "#9b60ff"], ["blue", "#357cff"], ["green", "#00e5a0"]].map(([name, color]) => <button type="button" key={name} onClick={() => setAccent(name)} className={`h-3 w-3 rounded-full ${accent === name ? "ring-2 ring-white" : ""}`} style={{ backgroundColor: color }} aria-label={`Use ${name} accent`} />)}</span></div></div><p className="mb-2 mt-4 text-[7px] font-bold uppercase text-white/50">Notifications central</p><div className="space-y-1.5"><SettingRow label="Push Notifications" active={settings[0]} onClick={() => flip(0)} /><SettingRow label="Email Intelligence Digest" active={settings[1]} onClick={() => flip(1)} /><SettingRow label="Daily Sync Reminders" active={settings[2]} onClick={() => flip(2)} /></div><p className="mb-2 mt-4 text-[7px] font-bold uppercase text-white/50">Focus cycles engine</p><div className="space-y-1.5"><SettingRow label="Focus Timer Interval" value="25 minutes" /><SettingRow label="Relax Break Duration" value="5 minutes" /><SettingRow label="App Shield Blocklist" value="12 software modules" /></div><p className="mb-2 mt-4 text-[7px] font-bold uppercase text-white/50">Privacy protocol</p><div className="space-y-1.5"><SettingRow label="Developer Analytics Sharing" active={true} onClick={() => flip(0)} /><SettingRow label="Anonymized Cloud Storage" active={true} onClick={() => flip(2)} /><SettingRow label="Nexus Security Clear" value="Secured" /></div></div></PhoneFrame>;
}

export function NotificationsSettingsScreen() {
  const [alerts, setAlerts] = useState([true, true, true, true, false, true]);
  const rows = [["Task Alerts & Reminders", "Notify when priority target windows approach"], ["Focus Sessions Alarm", "Notify upon completion of standard focus intervals"], ["Habit Daily Reminder", "Notify at specified personal habit trigger metrics"], ["AI Analytical Insights", "Direct push application optimization summaries"], ["Weekly Cognitive Report", "Telemetry tracking of executive performance"], ["System Updates & Marketing", "General software updates and news"]];
  return <PhoneFrame><div className="relative min-h-[555px] pb-5 pt-5"><BackHeader title="Notifications" /><p className="mb-2 mt-6 text-[7px] font-bold uppercase text-white/50">Alert classifications</p><div className="space-y-1.5">{rows.map(([title, detail], index) => <div key={title} className="flex items-center justify-between rounded-lg border border-white/5 bg-[#110d28] px-2.5 py-2.5"><span className="max-w-[175px]"><b className="block text-[8px]">{title}</b><small className="block text-[6px] text-white/40">{detail}</small></span><Toggle active={alerts[index]} onClick={() => setAlerts(alerts.map((value, rowIndex) => rowIndex === index ? !value : value))} /></div>)}</div><div className="mt-3 rounded-xl border border-white/5 bg-[#110d28] p-3"><p className="text-[7px] font-bold uppercase text-white/45">Quiet hours protocol</p><div className="mt-3 flex items-center justify-between text-[8px]"><span>Start Timer<br /><b>10:00 PM</b></span><span className="text-white/35">to</span><span>End Timer<br /><b>07:00 AM</b></span></div></div></div></PhoneFrame>;
}

export function SubscriptionPlanScreen() {
  const [upgraded, setUpgraded] = useState(false);
  return <PhoneFrame><div className="relative min-h-[555px] pb-5 pt-5"><BackHeader title="Nexus Pro" /><div className="mt-4 rounded-xl border border-[#00c7e5] bg-gradient-to-br from-[#27195d] to-[#3b2478] p-3"><span className="rounded bg-[#00c7e5] px-2 py-1 text-[7px] font-bold text-[#06151d]">7-DAY FREE TRIAL</span><h2 className="mt-3 text-[15px] font-extrabold">Access Unlimited Intelligence</h2><div className="mt-3 space-y-1 text-[8px] text-white/70"><p className="text-[#00e5a0]">✓ Unlimited instant AI strategic chat</p><p className="text-[#00e5a0]">✓ Advanced cognitive telemetry</p><p className="text-[#00e5a0]">✓ Custom synthesized focus audio wave</p><p className="text-[#00e5a0]">✓ SSO multi-terminal secure cloud sync</p><p className="text-[#00e5a0]">✓ Priority server pipeline &amp; support</p></div></div><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-xl border border-white/5 bg-[#110d28] p-3 text-center"><p className="text-[7px] text-white/45">MONTHLY ENGINE</p><b className="text-[18px]">$9.99</b><small className="block text-[6px] text-white/40">Billed Month-to-Month</small></div><div className="rounded-xl border border-[#00c7e5] bg-[#110d28] p-3 text-center"><p className="text-[7px] text-[#00c7e5]">SAVE 33%</p><b className="text-[18px]">$6.66</b><small className="block text-[6px] text-white/40">$79.99 total billing</small></div></div>{upgraded ? <button type="button" onClick={() => setUpgraded(false)} className={`${primaryButton} mt-3 w-full`}>Nexus Pro Active</button> : <Link href="/checkout" className={`${primaryButton} mt-3 block w-full text-center`}>Upgrade to Nexus Pro</Link>}<p className="mt-3 text-center text-[6px] text-white/35">Terms of service apply. Restore previous cloud purchases.</p></div></PhoneFrame>;
}

export function HabitDetailScreen() {
  const [deleted, setDeleted] = useState(false);
  return <PhoneFrame><div className="relative min-h-[555px] pb-5 pt-5"><BackHeader title="Morning Meditation" action="Edit" />{deleted ? <div className="mt-20 text-center"><p className="text-[15px] font-bold">Habit deleted</p><button type="button" onClick={() => setDeleted(false)} className="mt-4 text-[9px] text-[#00c7e5]">Restore habit</button></div> : <><div className="mt-5 rounded-xl border border-white/5 bg-[#110d28] p-3"><p className="text-[7px] uppercase text-white/45">Current continuous streak</p><b className="mt-2 block text-[17px]">28 Days Active</b><span className="float-right -mt-5 text-[#00c7e5]">♧</span></div><div className="mt-3 grid grid-cols-3 gap-1.5">{[["94%", "Completion Rate"], ["32 Days", "Longest Streak"], ["124 cycles", "Total Completed"]].map(([value, label]) => <div key={label} className="rounded-lg border border-white/5 bg-[#110d28] p-2 text-center"><b className="text-[12px]">{value}</b><small className="mt-1 block text-[6px] text-white/40">{label}</small></div>)}</div><div className="mt-3 rounded-xl border border-white/5 bg-[#110d28] p-3"><p className="text-[7px] font-bold uppercase text-white/50">Completion patterns history</p><div className="mt-3 grid grid-cols-7 gap-2">{Array.from({ length: 28 }, (_, index) => <span key={index} className={`h-3.5 rounded-full ${index % 5 === 0 ? "bg-[#00c7e5]" : index % 3 === 0 ? "bg-[#126b81]" : "bg-[#092d40]"}`} />)}</div><div className="mt-2 grid grid-cols-7 text-center text-[6px] text-white/35">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day) => <span key={day}>{day}</span>)}</div></div><div className="mt-3 rounded-xl border border-white/5 bg-[#110d28] p-3 text-[8px]"><span className="text-white/45">Daily trigger alert time</span><b className="float-right">08:00 AM &nbsp; ◷</b></div><div className="mt-3 rounded-xl border border-white/5 bg-[#110d28] p-3 text-[8px]"><p className="text-[7px] font-bold uppercase text-white/50">Logged session entries</p><p className="mt-3 text-[#00c7e5]">Jan 28, 2026</p><p className="mt-1 text-[7px] text-white/55">Quiet mind, deep focus today. Session felt highly restorative.</p><p className="mt-3 text-[#00c7e5]">Jan 27, 2026</p><p className="mt-1 text-[7px] text-white/55">Slightly distracted at start, but unified focus loop recovered.</p></div><button type="button" onClick={() => setDeleted(true)} className="mt-3 w-full rounded-lg border border-[#ff385d] py-2.5 text-[8px] font-bold text-[#ff536b]">Delete Habit Protocol</button></>}</div></PhoneFrame>;
}