"use client";

import { useEffect, useState } from "react";
import { PhoneFrame } from "@/src/app/onboarding/page";
import { AppBottomNav } from "@/src/components/app-navigation";

const primaryButton = "rounded-lg bg-gradient-to-r from-[#4940ec] to-[#8c4eed] py-3 text-[10px] font-bold shadow-[0_7px_18px_rgba(100,71,238,0.3)]";

function AiNav({ active = "ai" }: { active?: "focus" | "ai" }) {
  return <AppBottomNav active={active} />;
}

export function FocusBreakScreen() {
  const [seconds, setSeconds] = useState(299);
  const [paused, setPaused] = useState(false);

  useEffect(() => {
    if (paused || seconds <= 0) return;
    const timer = window.setInterval(() => setSeconds((value) => value - 1), 1000);
    return () => window.clearInterval(timer);
  }, [paused, seconds]);

  return <PhoneFrame><div className="relative min-h-[555px] pb-20 pt-5"><div className="flex items-center justify-between text-[14px] text-white/50"><button type="button">‹</button><span className="text-[11px] font-bold text-white/80">Relax</span><button type="button">•••</button></div><div className="mt-9 flex flex-col items-center"><div className="relative flex h-28 w-28 items-center justify-center rounded-full border-[3px] border-[#00e5a0] text-[21px] font-extrabold shadow-[0_0_36px_rgba(0,229,160,0.35)]"><span className="absolute inset-2 rounded-full border border-[#00c7e5]/20" />{Math.floor(seconds / 60).toString().padStart(2, "0")}:{(seconds % 60).toString().padStart(2, "0")}<small className="absolute bottom-7 text-[6px] text-white/45">SHORT BREAK</small></div></div><div className="mt-8 rounded-xl border border-white/5 bg-[#110d28] p-3"><p className="text-[9px] font-bold">〽 &nbsp; Try a Box Breathing Exercise</p><p className="mt-1 text-[7px] text-white/45">Inhale 4s, Hold 4s, Exhale 4s, Hold 4s</p><button type="button" className="mt-3 text-[8px] text-[#00c7e5]">Guide Me ›</button></div><div className="mt-3 flex gap-2"><button type="button" onClick={() => setPaused(!paused)} className="flex-1 rounded-lg bg-[#0e1c35] py-3 text-[9px] font-semibold">{paused ? "Resume Break" : "Skip Break"}</button><button type="button" onClick={() => setSeconds((value) => value + 120)} className="flex-1 rounded-lg bg-[#00c78e] py-3 text-[9px] font-bold text-[#06151d]">+2m Break</button></div><div className="mt-3 rounded-xl border border-white/5 bg-[#110d28] p-3 text-[8px] text-white/65">◷ &nbsp; Next: Deep Work <span className="block pl-5 text-[7px] text-white/35">Target: 45 minutes</span></div><AiNav active="focus" /></div></PhoneFrame>;
}

export function AiChatScreen() {
  const [message, setMessage] = useState("");
  const [sent, setSent] = useState(false);
  return <PhoneFrame><div className="relative min-h-[555px] pb-20 pt-5"><div className="flex items-center justify-between"><h2 className="text-[18px] font-extrabold">Nexus AI</h2><span className="rounded-lg border border-white/10 p-1.5 text-[#00c7e5]">✣</span></div><div className="mt-4 flex gap-2"><span className="text-[#9b60ff]">✣</span><div className="rounded-xl border border-white/5 bg-[#110d28] p-3 text-[8px] leading-[1.45] text-white/75">Hello Alex! I&apos;ve analyzed your upcoming schedule. You have a busy afternoon. Would you like me to map out your top focus areas?</div></div><div className="mt-3 flex justify-end"><span className="rounded-xl bg-[#6742df] px-3 py-2 text-[8px]">What should I focus on today?</span></div><div className="mt-3 flex gap-2"><span className="text-[#9b60ff]">✣</span><div className="rounded-xl border border-[#9b60ff] bg-[#19133d] p-3 text-[8px] leading-[1.5] text-white/75">Based on deadlines and energy optimization, here is your plan:<br /><br /><span className="text-[#00c7e5]">•</span> Review product spec (Due tomorrow)<br /><span className="text-[#00c7e5]">•</span> Draft app architecture sync<br /><br /><span className="text-white/45">I suggest a 90-minute deep focus block starting at 10:00 AM before your 2:00 PM team sync.</span></div></div>{sent && <div className="mt-3 flex justify-end"><span className="rounded-xl bg-[#6742df] px-3 py-2 text-[8px]">{message}</span></div>}<form onSubmit={(event) => { event.preventDefault(); if (message.trim()) { setSent(true); setMessage(""); } }} className="absolute bottom-20 left-0 right-0 flex items-center gap-2 rounded-xl border border-white/10 bg-[#110d28] px-3 py-2"><span className="text-white/40">⌕</span><input value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Ask Nexus anything..." className="min-w-0 flex-1 bg-transparent text-[8px] outline-none placeholder:text-white/35" /><button type="submit" aria-label="Send message" className="text-[#00c7e5]">↑</button></form><AiNav /></div></PhoneFrame>;
}

export function AiInsightsScreen() {
  const [enabled, setEnabled] = useState(false);
  return <PhoneFrame><div className="relative min-h-[555px] pb-20 pt-5"><div className="flex items-center justify-between"><h2 className="text-[17px] font-extrabold">AI Insights</h2><span className="rounded-lg border border-white/10 p-1.5 text-[#00c7e5]">⌁</span></div><div className="mt-5 rounded-xl border border-white/5 bg-[#110d28] p-3"><div className="flex justify-between text-[7px] font-bold uppercase text-white/50"><span>Weekly focus trend</span><span className="text-[#00e5a0]">+14% vs last week</span></div><div className="mt-3 flex h-12 items-end justify-around">{[24, 35, 43, 30, 38, 18, 12].map((height, index) => <div key={index} className="flex flex-col items-center gap-1"><span className={`w-3 rounded-t ${index === 2 ? "bg-[#00c7e5]" : "bg-[#6d44c8]"}`} style={{ height }} /><small className="text-[6px] text-white/35">{["M", "T", "W", "T", "F", "S", "S"][index]}</small></div>)}</div></div><div className="mt-3 space-y-2"><div className="rounded-xl border border-white/5 bg-[#110d28] p-3"><p className="text-[9px] font-bold">◷ &nbsp; Peak Productivity Hours</p><p className="mt-1 text-[7px] text-white/45">Your most productive hours are 9:00 AM - 11:00 AM daily.</p><button type="button" className="mt-3 w-full rounded border border-[#00c7e5]/20 py-2 text-[7px] text-[#00c7e5]">Protect this block in calendar</button></div><div className="rounded-xl border border-white/5 bg-[#110d28] p-3"><p className="text-[9px] font-bold">▮ &nbsp; Tuesday Velocity</p><p className="mt-1 text-[7px] text-white/45">You completed 40% more high-priority tasks on Tuesdays.</p><button type="button" className="mt-3 w-full rounded border border-white/10 py-2 text-[7px] text-white/65">View Tuesday schedules</button></div><div className="rounded-xl border border-white/5 bg-[#110d28] p-3"><p className="text-[9px] font-bold">▣ &nbsp; Distraction Defense</p><p className="mt-1 text-[7px] text-white/45">Block social media during morning focus blocks to save ~45m/day.</p><button type="button" onClick={() => setEnabled(!enabled)} className={`mt-3 w-full rounded py-2 text-[7px] font-bold ${enabled ? "bg-[#00c78e] text-[#06151d]" : "bg-[#00c7e5] text-[#06151d]"}`}>{enabled ? "Smart Block Enabled" : "Enable Smart Block"}</button></div></div><AiNav /></div></PhoneFrame>;
}

export function DailyBriefingScreen() {
  const [started, setStarted] = useState(false);
  return <PhoneFrame><div className="relative min-h-[555px] pb-20 pt-5"><div className="flex items-center justify-between"><div><h2 className="text-[17px] font-extrabold">Daily Briefing</h2><p className="mt-1 text-[8px] text-[#00c7e5]">Thursday, January 29</p></div><span className="text-[#00c7e5]">☼</span></div><div className="mt-5 rounded-xl border border-white/5 bg-[#110d28] p-3"><p className="text-[14px] font-bold">62° &amp; Clear</p><p className="mt-1 text-[8px] text-white/45">San Francisco, CA <span className="float-right text-[20px] text-[#00c7e5]">☼</span></p></div><p className="mb-2 mt-5 text-[8px] font-bold uppercase text-white/50">Today&apos;s timeline</p><div className="space-y-2 text-[8px]"><div className="flex gap-2"><span className="w-10 text-[#00c7e5]">10:00 AM</span><span className="flex-1 rounded-lg border border-white/5 bg-[#110d28] px-3 py-2">Deep Work Focus Block</span></div><div className="flex gap-2"><span className="w-10 text-white/45">2:00 PM</span><span className="flex-1 rounded-lg border border-white/5 bg-[#110d28] px-3 py-2">Product Sync &amp; Align</span></div></div><p className="mb-2 mt-5 text-[8px] font-bold uppercase text-white/50">AI ordered priorities</p><div className="rounded-xl border border-white/5 bg-[#110d28] p-3 text-[8px]"><p className="font-bold">1. Review product specs <span className="float-right text-[#00c7e5]">Urgent</span></p><p className="mt-2 text-[7px] leading-[1.4] text-white/45">Reason: Due tomorrow and blocks design team development cycle.</p></div><div className="mt-3 rounded-xl border border-white/5 bg-[#062b3c]/60 p-3"><p className="text-[9px] font-bold text-[#00c7e5]">Coach insight</p><p className="mt-1 text-[8px] leading-[1.4] text-white/65">&quot;Focus is a muscle. Your morning window is when it&apos;s strongest. Let&apos;s make today count.&quot;</p></div><button type="button" onClick={() => setStarted(true)} className={`${primaryButton} mt-4 w-full`}>{started ? "Day started" : "Looks good, start my day"}</button><AiNav /></div></PhoneFrame>;
}