"use client";

import { useState } from "react";
import { PhoneFrame } from "@/src/app/onboarding/page";
import { AppBottomNav } from "@/src/components/app-navigation";

const primaryButton = "rounded-lg bg-gradient-to-r from-[#4940ec] to-[#8c4eed] py-3 text-[10px] font-bold shadow-[0_7px_18px_rgba(100,71,238,0.3)]";

function AiNav() {
  return <AppBottomNav active="ai" />;
}

export function AiSuggestionsScreen() {
  const [items, setItems] = useState(["task", "project", "habit"]);
  const remove = (item: string) => setItems((current) => current.filter((value) => value !== item));
  return <PhoneFrame><div className="relative min-h-[555px] pb-20 pt-5"><div className="flex items-center justify-between"><h2 className="text-[17px] font-extrabold">Suggestions</h2><span className="rounded-lg border border-white/10 p-1.5 text-[#00c7e5]">✣</span></div><div className="mt-5 space-y-3">{items.includes("task") && <div className="rounded-xl border border-white/5 bg-[#110d28] p-3"><p className="text-[7px] font-bold uppercase text-[#00c7e5]">▣ Task suggestion</p><p className="mt-2 text-[9px] font-bold">Reschedule Design Sync</p><p className="mt-1 text-[7px] leading-[1.4] text-white/45">You have two overlapping events at 2:00 PM. Suggest moving &quot;Design Sync&quot; to Friday 10:00 AM.</p><div className="mt-3 flex gap-2"><button type="button" onClick={() => remove("task")} className="flex-1 rounded-lg border border-white/10 py-2 text-[8px] text-white/60">Dismiss</button><button type="button" onClick={() => remove("task")} className="flex-1 rounded-lg bg-[#00c7e5] py-2 text-[8px] font-bold text-[#06151d]">Reschedule</button></div></div>}{items.includes("project") && <div className="rounded-xl border border-white/5 bg-[#110d28] p-3"><p className="text-[7px] font-bold uppercase text-[#9b60ff]">☷ Project breakdown</p><p className="mt-2 text-[9px] font-bold">Nexus App Architecture Draft</p><p className="mt-1 text-[7px] leading-[1.4] text-white/45">This is a very large task. AI recommends breaking it down into 3 subtasks to prevent procrastination.</p><div className="mt-3 flex gap-2"><button type="button" onClick={() => remove("project")} className="flex-1 rounded-lg border border-white/10 py-2 text-[8px] text-white/60">Ignore</button><button type="button" onClick={() => remove("project")} className="flex-1 rounded-lg bg-[#8c50e8] py-2 text-[8px] font-bold">Break Down</button></div></div>}{items.includes("habit") && <div className="rounded-xl border border-white/5 bg-[#110d28] p-3"><p className="text-[7px] font-bold uppercase text-[#00e5a0]">＋ Habit optimization</p><p className="mt-2 text-[9px] font-bold">Introduce hydration habit</p><p className="mt-1 text-[7px] leading-[1.4] text-white/45">Your afternoon dips appear around 3:00 PM. Drinking water is correlated with sustained focus during this window.</p><div className="mt-3 flex gap-2"><button type="button" onClick={() => remove("habit")} className="flex-1 rounded-lg border border-white/10 py-2 text-[8px] text-white/60">Skip</button><button type="button" onClick={() => remove("habit")} className="flex-1 rounded-lg bg-[#00c78e] py-2 text-[8px] font-bold text-[#06151d]">Add Habit</button></div></div>}</div><AiNav /></div></PhoneFrame>;
}

export function AiWeeklyReviewScreen() {
  const [goalsSet, setGoalsSet] = useState(false);
  return <PhoneFrame><div className="relative min-h-[555px] pb-20 pt-5"><div className="flex items-center justify-between"><div><h2 className="text-[17px] font-extrabold">Weekly Review</h2><p className="mt-1 text-[8px] text-white/45">Week 4: Jan 22 - Jan 28</p></div><span className="rounded-lg border border-white/10 p-1.5 text-[#00c7e5]">▥</span></div><div className="mt-5 grid grid-cols-3 gap-2"><div className="rounded-lg bg-[#110d28] p-2"><b className="text-[#00c7e5]">24</b><small className="block text-[6px] text-white/40">Tasks Done</small></div><div className="rounded-lg bg-[#110d28] p-2"><b className="text-[#9b60ff]">14.5h</b><small className="block text-[6px] text-white/40">Focus Time</small></div><div className="rounded-lg bg-[#110d28] p-2"><b className="text-[#00e5a0]">92%</b><small className="block text-[6px] text-white/40">Habit Rate</small></div></div><p className="mb-2 mt-5 text-[8px] font-bold uppercase text-white/50">Weekly wins</p><div className="space-y-2 text-[8px]"><div className="rounded-lg border border-white/5 bg-[#110d28] p-2 text-white/70">✓ &nbsp; Consistently completed focus blocks early in the day.</div><div className="rounded-lg border border-white/5 bg-[#110d28] p-2 text-white/70">✓ &nbsp; Hit a 12-day streak on morning meditation.</div></div><div className="mt-3 rounded-xl border border-[#9b60ff] bg-[#19133d] p-3 text-[8px] leading-[1.45] text-white/65"><b className="text-white">Recommendations for Next Week</b><p className="mt-2">You tend to delay design reviews on Thursday afternoons. I suggest scheduling those reviews on Tuesdays.</p></div><button type="button" onClick={() => setGoalsSet(true)} className={`${primaryButton} mt-4 w-full`}>{goalsSet ? "Next Week's Goals Set" : "Set Next Week's Goals"}</button><AiNav /></div></PhoneFrame>;
}

export function AiGoalPlanningScreen() {
  const [accepted, setAccepted] = useState(false);
  return <PhoneFrame><div className="relative min-h-[555px] pb-20 pt-5"><div className="flex items-center justify-between"><h2 className="text-[17px] font-extrabold">Goal Planning</h2><span className="rounded-lg border border-white/10 p-1.5 text-[#00c7e5]">◎</span></div><div className="mt-5 rounded-xl border border-white/5 bg-[#110d28] p-3"><p className="text-[7px] font-bold uppercase text-[#00c7e5]">Active goal</p><p className="mt-2 text-[10px] font-bold">Launch Nexus Beta App</p><p className="mt-1 text-[7px] text-white/45">Target Deadline: March 31, 2026</p></div><p className="mb-2 mt-5 text-[8px] font-bold uppercase text-white/50">AI broken roadmap</p><div className="space-y-2"><div className="rounded-xl border border-white/5 bg-[#110d28] p-3 text-[8px]"><b>Milestone 1: Spec Review</b><span className="float-right text-[#00c7e5]">Feb 15</span><p className="mt-2 text-[7px] text-white/45">Required: Sync with tech leads, review specs, verify requirements.</p><small className="mt-2 block text-[7px] text-[#9b60ff]">• No active blockers detected.</small></div><div className="rounded-xl border border-white/5 bg-[#110d28] p-3 text-[8px]"><b>Milestone 2: UI &amp; Dev Align</b><span className="float-right text-white/45">Mar 01</span><p className="mt-2 text-[7px] text-white/45">Required: Developer workspace setup, component system exports.</p><small className="mt-2 block text-[7px] text-[#ffb11b]">• Dependency: Component definitions required</small></div></div><div className="mt-4 flex gap-2"><button type="button" onClick={() => setAccepted(false)} className="flex-1 rounded-lg border border-white/10 py-3 text-[8px] text-white/70">Adjust Plan</button><button type="button" onClick={() => setAccepted(true)} className="flex-1 rounded-lg bg-[#00c7e5] py-3 text-[8px] font-bold text-[#06151d]">{accepted ? "Plan Accepted" : "Accept Plan"}</button></div><AiNav /></div></PhoneFrame>;
}

export function AiCoachingScreen() {
  const [scheduled, setScheduled] = useState(false);
  return <PhoneFrame><div className="relative min-h-[555px] pb-20 pt-5"><div className="flex items-center justify-between"><h2 className="text-[17px] font-extrabold">Productivity Coach</h2><span className="rounded-lg border border-white/10 p-1.5 text-[#00c7e5]">♙</span></div><div className="mt-5 flex gap-2 rounded-xl border border-white/5 bg-[#110d28] p-3 text-[8px] leading-[1.45] text-white/70"><span className="text-[#9b60ff]">♙</span><p>Hi Alex. I noticed you postponed &quot;Nexus Architecture Draft&quot; three times this week. Procrastination usually comes from task ambiguity. Let&apos;s tackle it.</p></div><div className="mt-3 rounded-xl border border-[#9b60ff] bg-[#19133d] p-3 text-[8px] leading-[1.45] text-white/70"><b className="text-[#9b60ff]">✣ COACH RECOMMENDATION</b><p className="mt-2">&quot;Start with just a 15-minute skeleton draft. Don&apos;t worry about completeness. Once you start, momentum takes care of the rest.&quot;</p></div><div className="mt-3 rounded-xl border border-white/5 bg-[#110d28] p-3 text-[8px] text-white/70"><span className="mr-2 text-[#9b60ff]">⊞</span>Generated action item<p className="mt-2">Create 15-min draft task for 10:00 AM</p></div><button type="button" onClick={() => setScheduled(true)} className={`${primaryButton} mt-4 w-full`}>{scheduled ? "Follow-up Scheduled" : "Schedule Follow-up Sync"}</button><AiNav /></div></PhoneFrame>;
}