import { PhoneFrame } from "@/src/app/onboarding/page";
import { AppBottomNav } from "@/src/components/app-navigation";

const buttonClassName = "rounded-lg bg-gradient-to-r from-[#4940ec] to-[#8c4eed] py-3 text-[10px] font-bold shadow-[0_7px_18px_rgba(100,71,238,0.3)]";

function ScorePill({ evening = false }: { evening?: boolean }) {
  return <span className={`rounded-full px-2 py-1 text-[8px] font-bold ${evening ? "bg-[#083d35] text-[#00e5a0]" : "bg-[#092d40] text-[#00c7e5]"}`}>✣ {evening ? "96" : "85"} Score</span>;
}

function Priority({ title, time, complete = false, color = "#00c7e5" }: { title: string; time: string; complete?: boolean; color?: string }) {
  return <div className="flex items-center gap-2 rounded-lg border border-white/5 bg-[#100b2b]/80 px-2 py-2"><span className={`flex h-3.5 w-3.5 items-center justify-center rounded border text-[8px] ${complete ? "border-[#00c7e5] bg-[#00c7e5]/20 text-[#00c7e5]" : "border-white/20"}`}>{complete ? "✓" : ""}</span><div className="min-w-0 flex-1"><p className={`truncate text-[9px] ${complete ? "text-white/45 line-through" : "text-white/80"}`}>{title}</p><p className="text-[7px] text-white/35">{time}</p></div><span className="h-1.5 w-1.5 rounded-full" style={{ backgroundColor: color }} /></div>;
}

export function CompletionWelcomeScreen() {
  return <PhoneFrame><div className="relative flex min-h-[555px] flex-col items-center justify-end pb-10 text-center"><div className="relative mb-8 flex h-24 w-24 items-center justify-center rounded-full border-[3px] border-[#00c7e5] text-[19px] font-extrabold text-white shadow-[0_0_24px_rgba(0,199,229,0.2)]"><span className="absolute inset-2 rounded-full border border-[#8e52ff] border-l-transparent" />85%<small className="absolute bottom-5 text-[6px] font-bold text-[#00c7e5]">READY SCORE</small></div><h2 className="text-[18px] font-extrabold">You&apos;re All Set!</h2><p className="mt-3 max-w-[220px] text-[10px] leading-[1.55] text-white/50">Welcome to Nexus, Alex. We&apos;ve configured your daily framework to target <span className="text-[#00c7e5]">Productivity</span>, optimize <span className="text-[#00c7e5]">Habits</span>, and enhance <span className="text-[#00c7e5]">Focus</span>.</p><div className="mt-5 w-full rounded-lg border border-white/5 bg-[#110d28] px-3 py-2 text-left text-[8px] text-white/65">◉ &nbsp; Focus profiling initialized successfully.</div><button type="button" className={`${buttonClassName} mt-16 w-full`}>Start Using Nexus</button></div></PhoneFrame>;
}

export function HomeDashboardScreen({ evening = false }: { evening?: boolean }) {
  return <PhoneFrame><div className="relative min-h-[555px] pb-20 pt-5"><div className="flex items-start justify-between"><div><h2 className="text-[16px] font-extrabold">Good {evening ? "evening" : "morning"}, Alex</h2><p className="mt-1 text-[8px] text-white/45">Thursday, Jan 29</p></div><ScorePill evening={evening} /></div>{evening ? <div className="mt-5 rounded-xl border border-[#8c50e8]/30 bg-[#392174]/75 p-3"><p className="text-[9px] font-bold">✣ DAILY REFLECTION</p><p className="mt-2 text-[9px] leading-[1.5] text-white/65">Take 2 minutes to summarize your wins and structure tomorrow&apos;s blueprint.</p><button type="button" className={`${buttonClassName} mt-3 w-24 py-2`}>Reflect Now</button></div> : <div className="mt-5 rounded-xl border border-white/5 bg-[#110d28] p-3 text-[8px] leading-[1.5] text-white/65">✣ &nbsp; Your AI assistant suggests focusing on <span className="text-[#00c7e5]">3 priority tasks</span> today before your 2:00 PM sync.</div>}<p className="mb-2 mt-5 text-[8px] font-bold uppercase text-white/50">{evening ? "Completed priorities" : "Today&apos;s priorities"}</p><div className="space-y-2">{evening ? <><Priority title="Review product spec document" time="9:30 AM" complete /><Priority title="Sync with design developers" time="11:00 AM" complete /><Priority title="Nexus app architecture draft" time="3:30 PM" complete /></> : <><Priority title="Review product spec document" time="9:30 AM" complete /><Priority title="Sync with design developers" time="11:00 AM" color="#8c50e8" /><Priority title="Nexus app architecture draft" time="3:30 PM" color="#8c50e8" /></>}</div><p className="mb-2 mt-5 text-[8px] font-bold uppercase text-white/50">Performance &amp; focus</p><div className="grid grid-cols-2 gap-2"><div className="flex h-20 flex-col items-center justify-center rounded-xl border border-white/5 bg-[#100b2b]"> <span className="text-[15px] text-[#00c7e5]">{evening ? "11/12" : "7/12"}</span><span className="mt-2 text-[7px] text-white/35">Tasks Completed</span></div><div className="space-y-2"><div className="rounded-lg border border-white/5 bg-[#100b2b] px-2 py-2 text-[8px]">◷ &nbsp; <b>{evening ? "4h 30m" : "2h 15m"}</b><span className="block pl-4 text-[7px] text-white/35">Focus Time Today</span></div><div className="rounded-lg border border-white/5 bg-[#100b2b] px-2 py-2 text-[8px]">♧ &nbsp; <b>12 Days</b><span className="block pl-4 text-[7px] text-white/35">Habit Streak</span></div></div></div><p className="mb-2 mt-5 text-[8px] font-bold uppercase text-white/50">Upcoming timeline</p><div className="rounded-lg border border-white/5 bg-[#100b2b] px-2 py-3 text-[8px] text-white/70"><span className="mr-2 rounded bg-[#27165b] px-1 py-1 text-[#8c50e8]">{evening ? "9:00 PM" : "2:00 PM"}</span>{evening ? "Daily retrospective review" : "Project alignment sync"}<span className="float-right">›</span></div><AppBottomNav active="home" /></div></PhoneFrame>;
}

export function TasksInboxScreen() {
  const tasks = [["Refactor core layout system", "Today, 2:00 PM", "Work", "#ff385d"], ["Design review prep", "Today, 4:30 PM", "Work", "#ff9f18"], ["Pick up groceries", "Tomorrow, 10:00 AM", "Personal", "#718096"], ["Finish Nexus branding guidelines", "Jan 31", "Work", "#357cff"], ["Gym cardio session", "Feb 1", "Health", "#718096"], ["Launch marketing copy drafts", "Feb 3", "Side Project", "#ff9f18"]] as const;
  return <PhoneFrame><div className="relative min-h-[555px] pb-20 pt-5"><div className="flex items-center justify-between"><h2 className="text-[18px] font-extrabold">Tasks</h2><span className="flex h-6 w-6 items-center justify-center rounded-lg border border-white/10 text-[16px] text-white/80">+</span></div><div className="mt-5 flex gap-1.5 text-[8px]"><span className="rounded-full bg-[#00c7e5] px-3 py-1.5 font-bold text-[#06151d]">All</span><span className="rounded-full border border-white/10 px-3 py-1.5 text-white/60">Today</span><span className="rounded-full border border-white/10 px-3 py-1.5 text-white/60">Upcoming</span><span className="rounded-full border border-white/10 px-3 py-1.5 text-white/60">Completed</span></div><div className="mt-3 space-y-2">{tasks.map(([title, time, category, color], index) => <div key={title} className="flex items-center gap-2 rounded-xl border border-white/5 bg-[#100b2b]/85 px-2 py-2.5"><span className={`flex h-3.5 w-3.5 items-center justify-center rounded border ${index === 3 ? "border-[#00c7e5] bg-[#00c7e5]/20 text-[8px] text-[#00c7e5]" : "border-white/20"}`}>{index === 3 ? "✓" : ""}</span><div className="min-w-0 flex-1"><p className={`truncate text-[9px] ${index === 3 ? "text-white/45 line-through" : "text-white/80"}`}>{title}</p><p className="mt-1 text-[7px] text-white/35">{time} <span className="ml-1 rounded bg-[#28165a] px-1 text-[6px]" style={{ color }}>{category}</span></p></div><span className="h-1.5 w-1.5 rounded-full" style={{ backgroundColor: color }} /></div>)}</div><AppBottomNav active="tasks" /></div></PhoneFrame>;
}