"use client";

import { useState } from "react";
import { PhoneFrame } from "@/src/app/onboarding/page";
import { AppBottomNav } from "@/src/components/app-navigation";

const primaryButton = "rounded-lg bg-gradient-to-r from-[#4940ec] to-[#8c4eed] py-3 text-[10px] font-bold shadow-[0_7px_18px_rgba(100,71,238,0.3)]";

function FocusNav() {
  return <AppBottomNav active="focus" />;
}

export function FocusSessionSetupScreen() {
  const [duration, setDuration] = useState("45m");
  const [sound, setSound] = useState("Lo-fi");
  const [blocked, setBlocked] = useState([true, true, true, false, false]);
  const apps = ["▣  Instagram", "♧  Twitter", "⊗  TikTok", "▹  YouTube", "⊗  Reddit"];

  return <PhoneFrame><div className="relative min-h-[555px] pb-20 pt-5"><div className="flex items-center gap-3"><span className="text-[18px] text-white/60">‹</span><h2 className="text-[15px] font-extrabold">Configure Session</h2></div><p className="mb-2 mt-6 text-[7px] font-bold uppercase text-white/50">Set duration</p><div className="flex gap-1.5">{["25m", "45m", "60m", "90m", "Custom"].map((item) => <button type="button" onClick={() => setDuration(item)} key={item} className={`rounded-lg px-2 py-2 text-[8px] ${duration === item ? "bg-[#6c43ed] font-bold" : "border border-white/10 bg-[#110d28] text-white/65"}`}>{item}</button>)}</div><div className="mb-2 mt-5 flex justify-between text-[7px] font-bold uppercase text-white/50"><span>Block distractions</span><button type="button" className="text-[#00c7e5]" onClick={() => setBlocked(blocked.map(() => true))}>Block All</button></div><div className="space-y-1.5 rounded-xl border border-white/5 bg-[#110d28] p-2">{apps.map((app, index) => <button type="button" key={app} onClick={() => setBlocked(blocked.map((value, appIndex) => appIndex === index ? !value : value))} className="flex w-full items-center justify-between border-b border-white/5 py-1.5 text-left text-[9px] text-white/75 last:border-0"><span>{app}</span><span className={`h-3.5 w-6 rounded-full p-0.5 ${blocked[index] ? "bg-[#9b60ff]" : "bg-white/15"}`}><span className={`block h-2.5 w-2.5 rounded-full bg-white transition-transform ${blocked[index] ? "translate-x-2.5" : ""}`} /></span></button>)}</div><p className="mb-2 mt-5 text-[7px] font-bold uppercase text-white/50">Background sound</p><div className="flex gap-1.5">{["None", "Rain", "Lo-fi", "White Noise", "Forest"].map((item) => <button type="button" onClick={() => setSound(item)} key={item} className={`rounded-full px-2 py-1.5 text-[7px] ${sound === item ? "bg-[#00c7e5] font-bold text-[#06151d]" : "bg-[#110d28] text-white/65"}`}>{item}</button>)}</div><button type="button" className={`${primaryButton} mt-5 w-full`}>▷ Start {duration} Session</button><FocusNav /></div></PhoneFrame>;
}

export function FocusSessionCompleteScreen() {
  return <PhoneFrame><div className="relative flex min-h-[555px] flex-col justify-end pb-20 text-center"><div className="mb-5 flex h-14 w-14 items-center justify-center self-center rounded-full border-2 border-[#00c7e5] text-2xl text-[#00c7e5] shadow-[0_0_30px_rgba(0,199,229,0.3)]">♧</div><h2 className="text-[19px] font-extrabold">Great Work!</h2><p className="mt-1 text-[9px] text-white/45">You completed your focus target</p><div className="mt-5 rounded-xl border border-white/5 bg-[#12345a]/80 p-3 text-left text-[9px]"><p className="mb-3 text-[7px] font-bold uppercase text-white/50">Session summary</p><div className="space-y-3 text-white/50"><p>Focus Mode <b className="float-right text-white/80">Deep Work</b></p><p>Duration Completed <b className="float-right text-white/80">45 minutes</b></p><p>Distractions Blocked <b className="float-right text-[#ff536b]">47 Notifications</b></p><p>Focus Rating <b className="float-right text-[#00c7e5]">☆ ☆ ☆ ☆ ☆</b></p></div></div><div className="mt-4 rounded-xl border border-white/5 bg-[#110d28] p-3 text-left"><p className="text-[8px] font-bold text-white/80">♧ &nbsp; Streak Updated!</p><p className="mt-1 text-[7px] text-white/45">You are on a 13-day focus habit streak.</p></div><button type="button" className={`${primaryButton} mt-3 w-full`}>⇧ Share Achievement</button><button type="button" className="mt-2 w-full rounded-lg border border-white/10 bg-[#0d0924] py-3 text-[10px] text-white/75">Back to Focus</button><FocusNav /></div></PhoneFrame>;
}

export function FocusAppBlockingScreen() {
  const [apps, setApps] = useState([true, true, true, false]);
  const names = ["▣  Instagram", "⊗  TikTok", "♧  Twitter", "✣  Slack"];
  return <PhoneFrame><div className="relative min-h-[555px] pb-20 pt-5"><div className="flex items-center justify-between"><div><h2 className="text-[17px] font-extrabold">App Blocking</h2><p className="text-[8px] text-white/45">Minimize screen-time distractions</p></div><button type="button" className="flex h-6 w-6 items-center justify-center rounded-lg border border-white/10 text-[16px]">+</button></div><div className="mt-5 rounded-xl border border-white/5 bg-[#110d28] p-3"><p className="text-[9px] text-[#00c7e5]">♧</p><p className="mt-2 text-[14px] font-bold">1h 45m Saved</p><p className="mt-1 text-[7px] text-white/40">Screen time reduced today vs avg</p></div><p className="mb-2 mt-5 text-[7px] font-bold uppercase text-white/50">Blocking active rules</p><div className="space-y-2">{names.map((name, index) => <button type="button" key={name} onClick={() => setApps(apps.map((value, appIndex) => appIndex === index ? !value : value))} className="flex w-full items-center justify-between rounded-xl border border-white/5 bg-[#110d28] px-3 py-3 text-left text-[9px] text-white/75"><span>{name}<small className="block pl-4 text-[7px] text-white/35">{index === 3 ? "12m" : index === 0 ? "45m" : "10m"} spent today</small></span><span className={`h-3.5 w-6 rounded-full p-0.5 ${apps[index] ? "bg-[#00c7e5]" : "bg-white/15"}`}><span className={`block h-2.5 w-2.5 rounded-full bg-white transition-transform ${apps[index] ? "translate-x-2.5" : ""}`} /></span></button>)}</div><p className="mb-2 mt-5 text-[7px] font-bold uppercase text-white/50">Automatic schedules</p><div className="space-y-2 rounded-xl border border-white/5 bg-[#110d28] p-3 text-[8px] text-white/65"><p>▣ &nbsp; Work Hours Block <span className="float-right text-white/40">9:00 AM - 5:30 PM</span></p><p>◷ &nbsp; Wind-down Mode <span className="float-right text-white/40">10:00 PM - 7:00 AM</span></p></div><FocusNav /></div></PhoneFrame>;
}

export function FocusStatsScreen() {
  const [period, setPeriod] = useState("Week");
  return <PhoneFrame><div className="relative min-h-[555px] pb-20 pt-5"><div className="flex items-center justify-between"><h2 className="text-[17px] font-extrabold">Focus Stats</h2><div className="flex gap-1 text-[7px]">{["Day", "Week", "Month"].map((item) => <button type="button" onClick={() => setPeriod(item)} key={item} className={`rounded px-2 py-1 ${period === item ? "bg-[#8c50e8] text-white" : "text-white/55"}`}>{item}</button>)}</div></div><div className="mt-5 grid grid-cols-2 gap-2"><div className="rounded-xl border border-white/5 bg-[#110d28] p-3"><p className="text-[7px] text-white/45">Total Focus Time</p><b className="text-[14px]">14h 20m</b><small className="mt-1 block text-[7px] text-[#00e5a0]">↗ 12% vs last week</small></div><div className="rounded-xl border border-white/5 bg-[#110d28] p-3"><p className="text-[7px] text-white/45">Sessions Finished</p><b className="text-[14px]">18</b><small className="mt-1 block text-[7px] text-[#00e5a0]">95% success rate</small></div></div><div className="mt-3 rounded-xl border border-white/5 bg-[#110d28] p-3"><div className="flex justify-between text-[7px] font-bold uppercase text-white/45"><span>Focus trend score</span><span>Avg 85</span></div><div className="mt-5 flex h-16 items-center justify-around"><svg viewBox="0 0 180 50" className="h-full w-full" role="img" aria-label={`${period} focus trend`}><polyline points="5,38 35,22 65,34 95,12 125,24 155,4 178,22" fill="none" stroke="#00c7e5" strokeWidth="2" /><circle cx="5" cy="38" r="3" fill="#00c7e5" /><circle cx="35" cy="22" r="3" fill="#00c7e5" /><circle cx="65" cy="34" r="3" fill="#00c7e5" /><circle cx="95" cy="12" r="3" fill="#00c7e5" /><circle cx="125" cy="24" r="3" fill="#00c7e5" /><circle cx="155" cy="4" r="3" fill="#00c7e5" /><circle cx="178" cy="22" r="3" fill="#00c7e5" /></svg></div></div><div className="mt-3 rounded-xl border border-white/5 bg-[#110d28] p-3"><p className="text-[7px] font-bold uppercase text-white/45">Breakdown by mode</p><div className="mt-3 flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-full border-[9px] border-[#00c7e5] border-r-[#9b60ff] text-[12px] font-bold">18</div><div className="space-y-2 text-[8px] text-white/65"><p><span className="mr-1 text-[#00c7e5]">●</span>Deep Work (50%)</p><p><span className="mr-1 text-[#9b60ff]">●</span>Creative (28%)</p><p><span className="mr-1 text-[#6754df]">●</span>Meditation (22%)</p></div></div></div><FocusNav /></div></PhoneFrame>;
}