"use client";

import { useState } from "react";
import { PhoneFrame } from "@/src/app/onboarding/page";
import { AppBackButton, AppBottomNav } from "@/src/components/app-navigation";

const primaryButton = "rounded-lg bg-gradient-to-r from-[#4940ec] to-[#8c4eed] py-3 text-[10px] font-bold shadow-[0_7px_18px_rgba(100,71,238,0.3)]";

function ProfileNav() {
  return <AppBottomNav active="profile" />;
}

function BackHeader({ title }: { title: string }) {
  return <div className="flex items-center gap-3"><AppBackButton fallback="/profile" /><h2 className="text-[15px] font-extrabold">{title}</h2></div>;
}

export function ProfileMainScreen() {
  const items = [["♙", "Edit Profile", "Update personal details"], ["◎", "Goals & Milestones", "Track annual objectives"], ["〽", "Habits", "Manage daily routines"], ["♧", "Notifications", "Preferences and alerts"], ["☷", "App Settings", "Configure space parameters"], ["▣", "Privacy & Legal", "Credential permissions"], ["ⓘ", "Help & Support", "Knowledge base documentation"]];
  const [loggedOut, setLoggedOut] = useState(false);
  return <PhoneFrame><div className="relative min-h-[555px] pb-20 pt-5"><h2 className="text-[18px] font-extrabold">Profile</h2><div className="mt-5 flex items-center gap-3 rounded-xl border border-white/5 bg-[#110d28] p-3"><div className="flex h-10 w-10 items-center justify-center rounded-full border-2 border-[#00c7e5] bg-[#1e3a5d] text-lg">A</div><div><p className="text-[10px] font-bold">Alex Rivera</p><p className="text-[7px] text-white/45">alex@nexus.ai</p><p className="text-[7px] text-[#00c7e5]">Member since Jan 2025</p></div></div><div className="mt-3 rounded-xl border border-white/5 bg-[#110d28] p-3"><p className="text-[7px] font-bold uppercase text-white/45">Productivity engine</p><div className="mt-3 flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-full border-4 border-[#00c7e5] text-[12px] font-bold">85</div><div><p className="text-[9px] font-bold">Optimal Focus State</p><p className="text-[7px] text-white/45">You are performing in the top 5% of deep focus cycles today.</p></div></div></div><div className="mt-3 grid grid-cols-3 gap-1.5">{[["1,247", "Completed"], ["342h", "Focused"], ["28d", "Streak"]].map(([value, label]) => <div key={label} className="rounded-lg border border-white/5 bg-[#110d28] p-2 text-center"><b className="text-[13px]">{value}</b><small className="block text-[6px] text-white/40">{label}</small></div>)}</div><div className="mt-3 rounded-xl border border-white/5 bg-[#110d28] p-2"><p className="text-[7px] font-bold uppercase text-white/45">Earned achievement level</p><div className="mt-3 flex justify-around text-[15px] text-[#9b60ff]"><span>♙</span><span>◎</span><span>◷</span><span>♧</span><span>✣</span></div></div><div className="mt-3 space-y-1.5">{items.map(([icon, title, detail]) => <button type="button" key={title} className="flex w-full items-center gap-2 rounded-lg border border-white/5 bg-[#110d28] px-2 py-2 text-left"><span className="text-[#00c7e5]">{icon}</span><span className="flex-1"><b className="block text-[8px]">{title}</b><small className="block text-[6px] text-white/40">{detail}</small></span><span className="text-white/40">›</span></button>)}</div><button type="button" onClick={() => setLoggedOut(true)} className="mt-3 w-full rounded-lg border border-[#ff385d] py-2 text-[8px] text-[#ff536b]">{loggedOut ? "Logged Out" : "Log Out"}</button><ProfileNav /></div></PhoneFrame>;
}

export function EditProfileScreen() {
  const [saved, setSaved] = useState(false);
  const [name, setName] = useState("Alex Rivera");
  return <PhoneFrame><div className="relative min-h-[555px] pb-20 pt-5"><BackHeader title="Edit Profile" /><div className="mx-auto mt-5 flex h-14 w-14 items-center justify-center rounded-full border-2 border-[#00c7e5] bg-[#1e3a5d] text-xl">A</div><form onSubmit={(event) => { event.preventDefault(); setSaved(true); }} className="mt-6 space-y-3"><label className="block text-[7px] font-bold text-white/50">FULL NAME<input value={name} onChange={(event) => setName(event.target.value)} className="mt-1 w-full rounded-lg border border-white/5 bg-[#110d28] px-3 py-2.5 text-[9px] font-normal text-white outline-none" /></label><label className="block text-[7px] font-bold text-white/50">EMAIL ADDRESS<input defaultValue="alex@nexus.ai" className="mt-1 w-full rounded-lg border border-white/5 bg-[#110d28] px-3 py-2.5 text-[9px] font-normal text-white outline-none" /></label><label className="block text-[7px] font-bold text-white/50">USERNAME<input defaultValue="alex_nexus" className="mt-1 w-full rounded-lg border border-white/5 bg-[#110d28] px-3 py-2.5 text-[9px] font-normal text-white outline-none" /></label><label className="block text-[7px] font-bold text-white/50">BIO<textarea defaultValue="Building a calm, high-performance life with AI. Designing tools for a better tomorrow." className="mt-1 h-14 w-full resize-none rounded-lg border border-white/5 bg-[#110d28] px-3 py-2.5 text-[9px] font-normal text-white outline-none" /></label><label className="block text-[7px] font-bold text-white/50">TIME ZONE<select defaultValue="GMT-5" className="mt-1 w-full rounded-lg border border-white/5 bg-[#110d28] px-3 py-2.5 text-[9px] font-normal text-white outline-none"><option value="GMT-5">GMT-5 (EST) — Dropdown Selector</option><option value="GMT+0">GMT+0 (UTC)</option></select></label><label className="block text-[7px] font-bold text-white/50">LANGUAGE<select defaultValue="English" className="mt-1 w-full rounded-lg border border-white/5 bg-[#110d28] px-3 py-2.5 text-[9px] font-normal text-white outline-none"><option>English (US) — Dropdown Selector</option><option>French</option></select></label><button type="submit" className={`${primaryButton} w-full`}>{saved ? "Changes Saved" : "Save Changes"}</button></form><ProfileNav /></div></PhoneFrame>;
}

export function GoalsMilestonesScreen() {
  const [added, setAdded] = useState(false);
  const goals = [["Read 24 books this year", "Step 3: Advanced AI Literature", "15/24 Books", "62%"], ["Exercise 4x per week", "Next session scheduled: Saturday morning", "3/4 this week", "75%"], ["Learn Spanish Language", "60% fluency target reached in focus metrics", "Level B1 Target", "58%"], ["Save $10,000 for development", "Core infrastructure funding allocation", "$7,200 achieved", "72%"]];
  return <PhoneFrame><div className="relative min-h-[555px] pb-20 pt-5"><BackHeader title="Goals" /><div className="mt-5 space-y-3">{goals.map(([title, detail, metric, percent]) => <div key={title} className="rounded-xl border border-white/5 bg-[#110d28] p-3"><div className="flex justify-between text-[9px] font-bold"><span>{title}</span><span className="text-[#00c7e5]">{metric}</span></div><p className="mt-1 text-[7px] text-white/40">{detail}</p><div className="mt-3 h-1 rounded-full bg-white/10"><div className="h-1 rounded-full bg-[#00c7e5]" style={{ width: percent }} /></div><div className="mt-2 flex justify-between text-[6px] text-white/35"><span>Start</span><span>Milestone 1</span><span>End Goal</span></div></div>)}{added && <div className="rounded-xl border border-[#00c7e5] bg-[#062b3c]/60 p-3 text-[8px] text-[#00c7e5]">New goal draft added.</div>}</div><button type="button" onClick={() => setAdded(true)} className="mt-3 w-full rounded-lg border border-[#00c7e5] py-3 text-[9px] font-bold text-[#00c7e5]">＋ Add New Goal</button><ProfileNav /></div></PhoneFrame>;
}

export function HabitsTrackerScreen() {
  const [habits, setHabits] = useState([true, true, false, false, true]);
  const names = [["Morning Meditation", "28d streak"], ["Read 30 min", "14d streak"], ["Exercise Workouts", "5d streak"], ["Technical Journaling", "0d streak"], ["No Social Media before noon", "45d streak"]];
  return <PhoneFrame><div className="relative min-h-[555px] pb-20 pt-5"><BackHeader title="Habits" /><p className="mb-2 mt-6 text-[7px] font-bold uppercase text-white/50">Today&apos;s habit checklist</p><div className="space-y-2">{names.map(([name, streak], index) => <button type="button" key={name} onClick={() => setHabits(habits.map((value, habitIndex) => habitIndex === index ? !value : value))} className="flex w-full items-center gap-2 rounded-xl border border-white/5 bg-[#110d28] px-2 py-3 text-left"><span className={`flex h-3.5 w-3.5 items-center justify-center rounded border text-[8px] ${habits[index] ? "border-[#00c7e5] bg-[#00c7e5]/20 text-[#00c7e5]" : "border-white/20"}`}>{habits[index] ? "✓" : ""}</span><span className={`flex-1 text-[8px] ${habits[index] ? "text-white/80" : "text-white/60"}`}>{name}</span><span className="text-[7px] text-[#00c7e5]">{streak}</span></button>)}</div><p className="mb-2 mt-5 text-[7px] font-bold uppercase text-white/50">Completion heatmap</p><div className="rounded-xl border border-white/5 bg-[#110d28] p-3"><div className="grid grid-cols-7 gap-1">{Array.from({ length: 35 }, (_, index) => <span key={index} className={`h-4 rounded-sm ${index % 5 === 0 ? "bg-[#110d28]" : index % 3 === 0 ? "bg-[#00c7e5]" : "bg-[#126b81]"}`} />)}</div><div className="mt-2 grid grid-cols-7 text-center text-[6px] text-white/35">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day) => <span key={day}>{day}</span>)}</div></div><button type="button" className="mt-4 w-full rounded-lg border border-[#00c7e5] py-3 text-[9px] font-bold text-[#00c7e5]">＋ Configure New Habit</button><ProfileNav /></div></PhoneFrame>;
}