import Link from "next/link";
import { PhoneFrame } from "@/src/app/onboarding/page";

const fieldClassName = "rounded-lg border border-white/5 bg-[#110d28] px-3 py-2.5 text-[10px] text-white/80";
const buttonClassName = "w-full rounded-lg bg-gradient-to-r from-[#4940ec] to-[#8c4eed] py-3 text-[10px] font-bold shadow-[0_7px_18px_rgba(100,71,238,0.3)]";

export function EmailVerificationScreen() {
  return <PhoneFrame><div className="relative flex min-h-[555px] flex-col items-center justify-end pb-10 text-center"><div className="mb-5 flex h-16 w-16 items-center justify-center rounded-2xl border border-white/10 bg-[#12102d] text-2xl text-[#00c7e5] shadow-[0_0_24px_rgba(0,199,229,0.12)]">✉<span className="absolute ml-12 mt-12 flex h-3.5 w-3.5 items-center justify-center rounded-full bg-[#1ed486] text-[8px] text-[#06151d]">✓</span></div><h2 className="text-[18px] font-extrabold">Check your email</h2><p className="mt-2 max-w-[220px] text-[9px] leading-[1.5] text-white/50">We&apos;ve sent a 6-digit verification code to <span className="text-white/75">alex@nexus.ai</span>. Please enter it below.</p><div className="mt-5 flex gap-1.5"><span className={`${fieldClassName} w-8 px-0`}>4</span><span className={`${fieldClassName} w-8 px-0`}>8</span><span className={`${fieldClassName} w-8 px-0`}>2</span><span className={`${fieldClassName} w-8 px-0`}>0</span><span className={`${fieldClassName} w-8 border-[#00c7e5] px-0 text-[#00c7e5]`}>1</span><span className={`${fieldClassName} w-8 px-0`}> </span></div><Link href="/personalization-setup" className={`${buttonClassName} mt-5 block text-center`}>Verify</Link><p className="mt-3 text-[9px] text-white/50">Didn&apos;t receive the code? <Link href="/email-verification" className="text-[#00c7e5]">Resend Code</Link></p><Link href="/Login" className="mt-14 text-[9px] text-white/50">Back to Log In</Link></div></PhoneFrame>;
}

export function PersonalizationScreen() {
  return <PhoneFrame><div className="relative flex min-h-[555px] flex-col justify-end pb-10"><div className="mb-4"><h2 className="text-[18px] font-extrabold leading-tight">Let&apos;s personalize your<br />experience</h2><p className="mt-2 text-[9px] text-white/45">Nexus refines its intelligence based on your daily targets.</p></div><p className="mb-2 text-[8px] font-bold uppercase text-[#00c7e5]">What are your main goals?</p><div className="flex flex-wrap gap-1.5"><span className="rounded-full border border-[#9959ff] bg-[#6e3bd3]/30 px-2.5 py-1 text-[8px]">Productivity</span><span className="rounded-full border border-[#9959ff] bg-[#6e3bd3]/30 px-2.5 py-1 text-[8px]">Habits</span><span className="rounded-full border border-[#9959ff] bg-[#6e3bd3]/30 px-2.5 py-1 text-[8px]">Focus</span><span className="rounded-full bg-[#110d28] px-2.5 py-1 text-[8px] text-white/60">Planning</span><span className="rounded-full bg-[#110d28] px-2.5 py-1 text-[8px] text-white/60">Health</span><span className="rounded-full bg-[#110d28] px-2.5 py-1 text-[8px] text-white/60">Learning</span></div><p className="mb-2 mt-4 text-[8px] font-bold uppercase text-[#00c7e5]">What&apos;s your biggest challenge?</p><div className="space-y-1.5">{["Time management", "Procrastination", "Distractions", "Organization"].map((item, index) => <div key={item} className={`flex items-center justify-between rounded-lg border px-3 py-2 text-[9px] ${index === 0 ? "border-[#00c7e5] bg-[#062b3c]/50" : "border-white/5 bg-[#110d28] text-white/70"}`}><span>{item}</span><span className={`h-3 w-3 rounded-full border ${index === 0 ? "border-[#00c7e5] bg-[#00c7e5]" : "border-white/25"}`} /></div>)}</div><Link href="/notification-permission" className={`${buttonClassName} mt-5 block text-center`}>Continue</Link></div></PhoneFrame>;
}

export function NotificationPermissionScreen() {
  return <PhoneFrame><div className="relative flex min-h-[555px] flex-col items-center justify-end pb-10 text-center"><div className="mb-5 flex h-16 w-16 items-center justify-center rounded-2xl border border-white/10 bg-[#12102d] text-3xl text-[#9959ff]">♧</div><h2 className="text-[20px] font-extrabold">Stay on Track</h2><p className="mt-3 max-w-[220px] text-[10px] leading-[1.55] text-white/50">Nexus analyzes your flow to trigger smart reminders only when you&apos;re receptive. Reclaim your focus without missing a beat.</p><div className="mt-5 w-full space-y-2 text-left"><div className="rounded-lg border border-white/5 bg-[#110d28] px-3 py-2 text-[9px] text-white/75">◉ &nbsp; Optimal focus session cues</div><div className="rounded-lg border border-white/5 bg-[#110d28] px-3 py-2 text-[9px] text-white/75">✣ &nbsp; AI-curated distraction blocker</div></div><Link href="/app-usage-permission" className={`${buttonClassName} mt-8 block text-center`}>Enable Notifications</Link><Link href="/app-usage-permission" className="mt-2 block w-full rounded-lg border border-white/5 bg-[#0d0924] py-3 text-[10px] font-semibold text-white/75">Maybe Later</Link></div></PhoneFrame>;
}

export function AppUsagePermissionScreen() {
  return <PhoneFrame><div className="relative flex min-h-[555px] flex-col items-center justify-end pb-10 text-center"><div className="mb-5 flex h-16 w-16 items-center justify-center rounded-2xl border border-[#00c7e5]/20 bg-[#0c1d31] text-3xl text-[#00c7e5]">♢</div><h2 className="text-[20px] font-extrabold">App Usage Access</h2><p className="mt-3 max-w-[225px] text-[10px] leading-[1.55] text-white/50">Nexus monitors screen-time metrics to auto-schedule deep focus times and safely filter distracting habits when you need clarity.</p><div className="mt-5 w-full rounded-lg border border-[#00c7e5]/20 bg-[#062b3c]/50 px-3 py-3 text-left text-[8px] leading-[1.45] text-white/65"><span className="mr-2 text-[#00c7e5]">♙</span>Your data is encrypted locally and is never shared with third parties.</div><Link href="/completion-welcome" className={`${buttonClassName} mt-12 block text-center`}>Grant Access</Link><Link href="/completion-welcome" className="mt-2 block w-full rounded-lg border border-white/5 bg-[#0d0924] py-3 text-[10px] font-semibold text-white/75">Skip for Now</Link></div></PhoneFrame>;
}