import { PhoneFrame } from "@/src/app/onboarding/page";
import { AppBackButton, AppBottomNav } from "@/src/components/app-navigation";

const primaryButton = "rounded-lg bg-gradient-to-r from-[#4940ec] to-[#8c4eed] py-3 text-[10px] font-bold shadow-[0_7px_18px_rgba(100,71,238,0.3)]";

function TaskNav() {
  return <AppBottomNav active="tasks" />;
}

function BackHeader({ title, action }: { title: string; action?: string }) {
  return <div className="flex items-center gap-3"><AppBackButton fallback="/tasks-inbox" /><h2 className="text-[15px] font-extrabold">{title}</h2>{action && <span className="ml-auto flex h-6 w-6 items-center justify-center rounded-lg border border-white/10 text-[15px] text-white/75">{action}</span>}</div>;
}

function Field({ label, value, tall = false }: { label: string; value: string; tall?: boolean }) {
  return <label className="block text-[7px] font-bold uppercase text-white/50">{label}<div className={`mt-1 rounded-lg border border-white/5 bg-[#110d28] px-3 py-2.5 text-[9px] font-normal normal-case text-white/70 ${tall ? "h-16 leading-[1.4]" : ""}`}>{value}</div></label>;
}

export function TaskDetailScreen() {
  return <PhoneFrame><div className="relative min-h-[555px] pb-20 pt-5"><BackHeader title="Task Details" /><h2 className="mt-6 text-[16px] font-extrabold">Refactor core layout system</h2><p className="mt-1 text-[8px] text-white/40">Added by AI assistant on Tuesday</p><div className="mt-4 rounded-xl border border-white/5 bg-[#19133d]/80 p-3 text-[9px]"><div className="grid grid-cols-2 gap-y-3 text-white/45"><span>Status</span><b className="text-right text-[#00c7e5]">● In Progress</b><span>Priority</span><b className="text-right text-[#ff536b]">● Urgent</b><span>Due Date</span><b className="text-right text-white/75">Today, 2:00 PM</b><span>Project</span><b className="text-right text-[#9b60ff]">Work</b></div></div><p className="mb-2 mt-5 text-[8px] font-bold uppercase text-white/50">Description</p><div className="rounded-xl border border-white/5 bg-[#110d28] p-3 text-[9px] leading-[1.5] text-white/65">Optimize the container auto-layout configurations across screens to ensure correct constraints are fully resolved on smaller device viewports.</div><p className="mb-2 mt-5 text-[8px] font-bold uppercase text-white/50">Subtasks (2/3)</p><div className="space-y-2">{["Map out constraint hierarchy", "Test layout wrapping boundaries", "Resolve nested padding conflicts"].map((item, index) => <div key={item} className="flex items-center gap-2 rounded-lg border border-white/5 bg-[#110d28] px-2 py-2 text-[8px] text-white/70"><span className={`flex h-3 w-3 items-center justify-center rounded border ${index < 2 ? "border-[#00c7e5] text-[#00c7e5]" : "border-white/20"}`}>{index < 2 ? "✓" : ""}</span><span className={index < 2 ? "line-through text-white/40" : ""}>{item}</span></div>)}</div><div className="mt-5 flex gap-2"><button type="button" className="flex-1 rounded-lg bg-[#00c7e5] py-3 text-[9px] font-bold text-[#06151d]">Complete Task</button><button type="button" className="w-8 rounded-lg border border-[#ff385d] text-[#ff385d]">♧</button></div><TaskNav /></div></PhoneFrame>;
}

export function TaskCreationScreen() {
  return <PhoneFrame><div className="relative min-h-[555px] pb-20 pt-5"><BackHeader title="Create New Task" /><div className="mt-6 space-y-4"><Field label="Task title" value="Write marketing copy edits" /><Field label="Description" value="Draft a series of short benefit statements targeting our early signups..." tall /><div className="grid grid-cols-2 gap-4"><Field label="Due date" value="▣  Tomorrow" /><Field label="Time" value="◷ 10:00 AM" /></div><div><p className="mb-2 text-[7px] font-bold uppercase text-white/50">Priority</p><div className="flex gap-1.5 text-[8px]"><span className="rounded-full border border-[#ff9f18] bg-[#5d321d] px-2 py-1 text-[#ffb246]">● High</span><span className="rounded-full border border-white/10 px-2 py-1 text-white/55">● Medium</span><span className="rounded-full border border-white/10 px-2 py-1 text-white/55">● Low</span></div></div><div className="rounded-lg border border-[#9b60ff] bg-[#29165b]/50 p-2 text-[8px] text-white/70">✣ &nbsp; AI: Schedule for tomorrow morning based on your current workload patterns.</div></div><button type="button" className={`${primaryButton} absolute bottom-20 left-5 right-5`}>Create Task</button><TaskNav /></div></PhoneFrame>;
}

const calendarTasks = [["09:30 AM", "Refactor core layout system", "#ff536b"], ["11:00 AM", "Design review prep", "#ff9f18"], ["03:30 PM", "Nexus architecture sync", "#357cff"]] as const;

export function TasksCalendarScreen() {
  return <PhoneFrame><div className="relative min-h-[555px] pb-20 pt-5"><BackHeader title="Calendar" action="▣" /><p className="mt-6 text-[10px] font-bold">January 2026</p><div className="mt-4 grid grid-cols-7 text-center text-[7px] text-white/40">{["M", "T", "W", "T", "F", "S", "S"].map((day) => <span key={day}>{day}</span>)}</div><div className="mt-3 grid grid-cols-7 gap-y-3 text-center text-[8px] text-white/65">{["26", "27", "28", "29", "30", "31", "1"].map((day) => <span key={day} className={day === "29" ? "mx-auto flex h-5 w-5 items-center justify-center rounded-full bg-[#00c7e5] font-bold text-[#06151d]" : ""}>{day}</span>)}</div><p className="mb-2 mt-6 text-[8px] font-bold uppercase text-white/50">Today&apos;s schedule</p><div className="space-y-2">{calendarTasks.map(([time, title, color]) => <div key={title} className="flex items-center gap-2"><span className="w-9 text-[7px] text-white/45">{time}</span><div className="flex flex-1 items-center gap-2 rounded-xl border border-white/5 bg-[#100b2b] px-2 py-2.5"><span className="h-3.5 w-3.5 rounded border border-white/20" /><div className="min-w-0 flex-1"><p className="truncate text-[9px] text-white/75">{title}</p><p className="text-[7px] text-white/35">Today &nbsp;•&nbsp; <span style={{ color }}>Work</span></p></div><span className="h-1.5 w-1.5 rounded-full" style={{ backgroundColor: color }} /></div></div>)}</div><TaskNav /></div></PhoneFrame>;
}

const projects = [["Work", "12 tasks", "58% complete", "#00c7e5", "w-3/5"], ["Personal", "5 tasks", "40% complete", "#9b60ff", "w-2/5"], ["Health", "3 tasks", "80% complete", "#00e5a0", "w-4/5"], ["Learning", "8 tasks", "15% complete", "#ffb11b", "w-[15%]"], ["Side Project", "4 tasks", "0% complete", "#ff9f3f", "w-0"]] as const;

export function TasksProjectsScreen() {
  return <PhoneFrame><div className="relative min-h-[555px] pb-20 pt-5"><BackHeader title="Projects" action="+" /><div className="mt-5 space-y-3">{projects.map(([name, count, progress, color, width]) => <div key={name} className="rounded-xl border border-white/5 bg-[#110d28]/90 p-3"><div className="flex items-center justify-between text-[9px]"><span className="font-semibold"><span className="mr-1.5 inline-block h-1.5 w-1.5 rounded-full" style={{ backgroundColor: color }} />{name}</span><span className="text-[7px] text-white/45">{count}</span></div><div className="mt-2 h-1 rounded-full bg-white/10"><div className={`h-1 rounded-full ${width}`} style={{ backgroundColor: color }} /></div><p className="mt-2 text-[7px] text-white/40">{progress}</p></div>)}</div><TaskNav /></div></PhoneFrame>;
}